export const AppleCategories = new Set<string>([
  'arts',
  'books',
  'design',
  'fashion & beauty',
  'food',
  'performing arts',
  'visual arts',
  'business',
  'careers',
  'entrepreneurship',
  'investing',
  'management',
  'marketing',
  'non-profit',
  'comedy',
  'comedy interviews',
  'improv',
  'stand-up',
  'education',
  'courses',
  'how to',
  'language learning',
  'self-improvement',
  'fiction',
  'comedy fiction',
  'drama',
  'science fiction',
  'government',
  'history',
  'health & fitness',
  'alternative health',
  'fitness',
  'medicine',
  'mental health',
  'nutrition',
  'sexuality',
  'kids & family',
  'education for kids',
  'parenting',
  'pets & animals',
  'stories for kids',
  'leisure',
  'animation & manga',
  'automotive',
  'aviation',
  'crafts',
  'games',
  'hobbies',
  'home & garden',
  'video games',
  'music',
  'music commentary',
  'music history',
  'music interviews',
  'news',
  'business news',
  'daily news',
  'entertainment news',
  'news commentary',
  'politics',
  'sports news',
  'tech news',
  'religion & spirituality',
  'buddhism',
  'christianity',
  'hinduism',
  'islam',
  'judaism',
  'religion',
  'spirituality',
  'science',
  'astronomy',
  'chemistry',
  'earth sciences',
  'life sciences',
  'mathematics',
  'natural sciences',
  'nature',
  'physics',
  'social sciences',
  'society & culture',
  'documentary',
  'personal journals',
  'philosophy',
  'places & travel',
  'relationships',
  'sports',
  'baseball',
  'basketball',
  'cricket',
  'fantasy sports',
  'football',
  'golf',
  'hockey',
  'rugby',
  'running',
  'soccer',
  'swimming',
  'tennis',
  'volleyball',
  'wilderness',
  'wrestling',
  'technology',
  'true crime',
  'tv & film',
  'after shows',
  'film history',
  'film interviews',
  'film reviews',
  'tv reviews',
]);

export function isAppleCategory(category?: string | null): boolean {
  if (!category) {
    return false;
  }
  return AppleCategories.has(category.trim().toLowerCase());
}
